/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bed_cream-colored_low_poly.glb 
Author: Moryak (https://sketchfab.com/_moryak_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bed-cream-colored-low-poly-ae5ae1da7dd444abae8ea14d9635a8dc
Title: Bed cream-colored Low poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/bed_cream-colored_low_poly.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.aeneoclsbdg000005_aeneoclsbdg000005_0.geometry}
          material={materials.aeneoclsbdg000005}
          position={[0, -8.066, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[96.122, 99.135, 29.838]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bed_cream-colored_low_poly.glb");
